export const PERMISSIONS = {
  TENANTS_VIEW: 'tenants.view',
  TENANTS_MANAGE: 'tenants.manage',
  BRANCHES_VIEW: 'branches.view',
  BRANCHES_MANAGE: 'branches.manage',
  USERS_VIEW: 'users.view',
  USERS_MANAGE: 'users.manage',
  ROLES_VIEW: 'roles.view',
  ROLES_MANAGE: 'roles.manage',
  PERMISSIONS_VIEW: 'permissions.view',
  DEVICES_VIEW: 'devices.view',
  DEVICES_REGISTER: 'devices.register',
  DEVICES_MANAGE: 'devices.manage',
  REGISTERS_VIEW: 'registers.view',
  REGISTERS_MANAGE: 'registers.manage',
  CATEGORIES_VIEW: 'categories.view',
  CATEGORIES_MANAGE: 'categories.manage',
  UNITS_VIEW: 'units.view',
  UNITS_MANAGE: 'units.manage',
  TAXES_VIEW: 'taxes.view',
  TAXES_MANAGE: 'taxes.manage',
  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_MANAGE: 'products.manage',
  MODIFIERS_VIEW: 'modifiers.view',
  MODIFIERS_MANAGE: 'modifiers.manage',
  DISCOUNTS_VIEW: 'discounts.view',
  DISCOUNTS_MANAGE: 'discounts.manage',
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_ADJUST: 'inventory.adjust',
  SHIFTS_VIEW: 'shifts.view',
  SHIFTS_OPEN: 'shifts.open',
  SHIFTS_CLOSE: 'shifts.close',
  TABLES_VIEW: 'tables.view',
  TABLES_MANAGE: 'tables.manage',
  ORDERS_VIEW: 'orders.view',
  ORDERS_CREATE: 'orders.create',
  ORDERS_UPDATE: 'orders.update',
  SALES_COMPLETE: 'sales.complete',
  SALES_VOID: 'sales.void',
  SALES_VOID_APPROVE: 'sales.void.approve',
  PAYMENTS_VIEW: 'payments.view',
  PRINTERS_VIEW: 'printers.view',
  PRINTERS_MANAGE: 'printers.manage',
  PRINT_JOBS_VIEW: 'print_jobs.view',
  PRINT_JOBS_REPRINT: 'print_jobs.reprint',
  PRINT_AGENT: 'print_agent.process',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const CORE_PERMISSION_CODES: readonly PermissionCode[] = Object.values(PERMISSIONS);
